-- TryBuy production baseline: nodeB (postgres)
-- Generated from the current TypeORM entity metadata; schema + required reference data only.
-- Import into an empty database. Do not run against an existing schema.

BEGIN;

CREATE TYPE "payments_status_enum" AS ENUM ('pending', 'completed', 'failed');

CREATE TABLE "inventory_reservations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "reservation_key" UUID NOT NULL,
  "inventory_id" BIGINT NOT NULL,
  "quantity" INTEGER NOT NULL,
  "status" VARCHAR(20) NOT NULL DEFAULT 'reserved',
  "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_inventory_reservation_key_item" UNIQUE ("reservation_key", "inventory_id")
);

CREATE TABLE "inventory_v2" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" BIGINT NOT NULL,
  "product_sku_id" BIGINT NULL,
  "sku" VARCHAR(100) NOT NULL,
  "available_stock" INTEGER NOT NULL DEFAULT 0,
  "reserved_stock" INTEGER NOT NULL DEFAULT 0,
  "minimum_stock" INTEGER NOT NULL DEFAULT 0,
  "location" VARCHAR(50) NULL,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "UQ_e905a916e8735161e2e11704544" UNIQUE ("sku"),
  CONSTRAINT "UQ_03c13890a00be173a3e04b73e06" UNIQUE ("product_id", "product_sku_id")
);

CREATE TABLE "payment_methods" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "key" VARCHAR(50) NOT NULL,
  "name" VARCHAR(100) NOT NULL,
  "description" VARCHAR(255) NOT NULL,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  PRIMARY KEY ("id"),
  CONSTRAINT "UQ_14dfd552829a60ecf16704a8ae2" UNIQUE ("key")
);

CREATE TABLE "payments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" BIGINT NULL,
  "order_ids" JSONB NULL,
  "amount" NUMERIC(12,2) NOT NULL,
  "status" "payments_status_enum" NOT NULL DEFAULT 'pending',
  "order_url" TEXT NULL,
  "transaction_id" VARCHAR(255) NULL,
  "app_trans_id" VARCHAR(50) NULL,
  "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE "reward_points" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" BIGINT NOT NULL,
  "order_id" BIGINT NOT NULL,
  "points" INTEGER NOT NULL,
  "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE INDEX "idx_inventory_reservation_key" ON "inventory_reservations" ("reservation_key");
CREATE INDEX "idx_inventory_product_id" ON "inventory_v2" ("product_id");
CREATE INDEX "idx_inventory_sku" ON "inventory_v2" ("sku");
CREATE INDEX "idx_payments_app_trans_id" ON "payments" ("app_trans_id") WHERE app_trans_id IS NOT NULL;
CREATE INDEX "idx_payments_order_id" ON "payments" ("order_id") WHERE order_id IS NOT NULL;


-- Required payment reference data; no transaction/demo records.
INSERT INTO "payment_methods" ("key", "name", "description", "is_active") VALUES
  ('zalopay', 'ZaloPay', 'Payment via ZaloPay', TRUE),
  ('vnpay', 'VNPay', 'Payment via VNPay', TRUE),
  ('cod', 'COD', 'Cash on delivery', TRUE);

CREATE TABLE "schema_migrations" (
  "id" TEXT PRIMARY KEY,
  "filename" TEXT NOT NULL,
  "checksum" CHAR(64) NOT NULL,
  "applied_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO "schema_migrations" ("id", "filename", "checksum") VALUES
  ('nodeB-20250621-001-add-inventory-reservations', 'database/add_inventory_reservations.sql', '1a7be46ecc602e650b3cbce99d11ad97b59e5e202fe4782ef12c44279c2c480a'),
  ('nodeB-20260707-001-add-payments-order-id-index', 'database/add_payments_order_id_index.sql', 'f8a710d41f8064b7a5b6429d6dfaaaa30f23a85f65f8b399901351cd6c55c4d9'),
  ('nodeB-20260707-002-add-payments-app-trans-id-index', 'database/add_payments_app_trans_id_index.sql', '328485247dee2ae784cde760ded9c25fcdab8bda3472f01e2a209bfa90e2e237');

COMMIT;

