export const TCP_HOST = "localhost";

export const PORT_TCP = {
  PRODUCT_TCP_PORT: 3006,
  PAYMENT_TCP_PORT: 3005,
  REWARD_TCP_PORT: 3004,
  USER_TCP_PORT: 3003,
  INVENTORY_TCP_PORT: 3002,
  ORDERS_TCP_PORT: 3001,
};

export const NAME_SERVICE_TCP = {
  PRODUCT_SERVICE: "PRODUCT_SERVICE",
  PAYMENT_SERVICE: "PAYMENT_SERVICE",
  REWARD_SERVICE: "REWARD_SERVICE",
  USER_SERVICE: "USER_SERVICE",
  INVENTORY_SERVICE: "INVENTORY_SERVICE",
  ORDERS_SERVICE: "ORDERS_SERVICE",
};
