version: "3.8"

services:
  # mysql:
  #   image: mysql:latest
  #   container_name: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123123
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - C:/Users/Quang Truong/Desktop/nginx-project/sql:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - C:/redis-data:/data
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user_vh
      RABBITMQ_DEFAULT_PASS: root1234
      RABBITMQ_DEFAULT_VHOST: rabbit-trybuy
    ports:
      - "5672:5672" # app connect
      - "15672:15672" # UI
    volumes:
      - C:/rabbitmq-data:/var/lib/rabbitmq
