export const EVENT = {
  ORDER_CREATED_EVENT: "order_created",
  ORDER_CANCELED_EVENT: "order_canceled",
  ORDER_STATUS_CHANGED_EVENT: "order.status_changed",
  ORDER_RETURN_REQUESTED_EVENT: "order.return_requested",
  ORDER_RETURN_APPROVED_EVENT: "order.return_approved",
  ORDER_RETURN_REJECTED_EVENT: "order.return_rejected",
  PAYMENT_COMPLETED_EVENT: "payment_completed",
  INVENTORY_STOCK_CHANGED_EVENT: "inventory.stock_changed",
  COMMENT_CREATED_EVENT: "social.comment_created",
  REPLY_CREATED_EVENT: "social.reply_created",
  BRAND_REVIEWED_EVENT: "product.brand_reviewed",
  CATEGORY_REVIEWED_EVENT: "product.category_reviewed",
  SKU_UPSERTED_EVENT: "sku.upserted",
  NOTIFY_USER_PUSH_EVENT: "notification.user_push",
};
